name: Build e Push da Imagem Docker

on:
  workflow_dispatch:
  # push:
  #   branches:
  #     - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Login no Azure Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build e Push da imagem
        uses: docker/build-push-action@v5
        with:
          context: ./KanbanApp/KanbanApp
          file: ./KanbanApp/KanbanApp/Dockerfile
          push: true
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/kanban-app:${{ github.sha }}